name: Deployment
 
on:
  repository_dispatch:
    types: [ deploy ]

env:
  PERSONAL_TOKEN: ${{ github.event.client_payload.token }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: samah603/import-repo
          token: ${{ env.PERSONAL_TOKEN }}
          persist-credentials: true
          ref: ${{ github.event.client_payload.branch }}
          
