name: Deployment
 
on:
  repository_dispatch:
    types: [deploy]
 
#env:
  #PERSONAL_TOKEN: ${{ github.event.client_payload.token }}
  #DATE: $(date '+%Y-%m-%d')
 
jobs:
  check:
    name: samah603/import-repo
    runs-on: ubuntu-latest
 
    steps:
      - name: Download Exported Secrets
        uses: actions/download-artifact@v2
        with:
          name: exported-secrets
          #path: .
          run: ls -R

      - name: Set Secrets
        run: |
          export $(cat exported-secrets.env | xargs)
          echo "Imported secrets successfully."
          
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: samah603/import-repo
          token: ${{ env.PERSONAL_TOKEN }} # `GH_PAT` is a secret that contains your PAT
          persist-credentials: true
          ref: ${{ github.event.client_payload.branch }}
      # - run: echo ${{ github.event.client_payload.token }}    
          
