name: Deployment
 
on:
  repository_dispatch:
    types: [ deploy ]

env:
  PERSONAL_TOKEN: ${{ github.event.client_payload.info.token }}
  BRANCH_NAME: ${{ github.event.client_payload.info.branch }}
  EMAIL_USERNAME: ${{ github.event.client_payload.gmail.user }}
  EMAIL_PASSWORD: ${{ github.event.client_payload.gmail.pass }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: samah603/import-repo
          token: ${{ env.PERSONAL_TOKEN }}
          persist-credentials: true
          ref: ${{ env.BRANCH_NAME }}
      - name: Show environment
        run: |
         echo "EMAIL_USERNAME=${{ env.EMAIL_USERNAME }}"
