name: Receive Repository Dispatch Event

on:
  repository_dispatch:
    types: [trigger-event]

jobs:
  process-payload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print some_variable
        run: echo "Some Variable: ${{ github.event.client_payload.some_variable }}"
